server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:${DB_MYSQL_PORT}/${DB_MYSQL_NAME}
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #        format_sql: true
  #    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  secret: ${JWT_SECRET_KEY}

base:
  url: ${STADIUM_BASE_URL}

springdoc:
  swagger-ui:
    tagsSorter: alpha
